# Generated by Django 5.0.6 on 2024-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='Song_Image',
            field=models.ImageField(blank=True, null=True, upload_to='song_Images'),
        ),
    ]
