# Generated by Django 5.0.6 on 2024-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_songdb_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='Song',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
