# Generated by Django 5.0.6 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_eventdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
