# Generated by Django 5.0.6 on 2024-06-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_eventdb_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdb',
            old_name='Date_time',
            new_name='Date',
        ),
    ]
