# Generated by Django 5.0.6 on 2024-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_date_time_eventdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdb',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
