# Generated by Django 5.0.6 on 2024-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_genredb'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='Performer1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer1Image',
            field=models.ImageField(blank=True, null=True, upload_to='Performer1image'),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer2Image',
            field=models.ImageField(blank=True, null=True, upload_to='Performer1image'),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer3Image',
            field=models.ImageField(blank=True, null=True, upload_to='Performer1image'),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer4Image',
            field=models.ImageField(blank=True, null=True, upload_to='Performer1image'),
        ),
    ]
