# Generated by Django 5.0.6 on 2024-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_eventdb_performer1_eventdb_performer1image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='Performer1role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer2role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer3role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='Performer4role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
